(self.AMP=self.AMP||[]).push({n:"amp-list",v:"1492569253368",f:(function(AMP){function e(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};var k=Object.prototype.toString;Date.now();self.log=self.log||{user:null,dev:null};var l=self.log;function m(){if(l.user)return l.user;throw Error("failed to call initLogConstructor");};function n(a,b){var c;a=a.__AMP_TOP||a;return p(a,a,b,void 0,c?c:void 0)}function r(a){return a.nodeType?n((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function p(a,b,c,d,f){var g=a.services;g||(g=a.services={});var h=g;(a=h[c])||(a=h[c]={obj:null,promise:null,resolve:null,build:null});a.obj||(a.obj=a.build?a.build():d?new d(b):f(b),a.resolve&&a.resolve(a.obj));return a.obj};var t,u;
function v(a){if("string"==typeof a){t||(t=self.document.createElement("a"),u=self.UrlCache||(self.UrlCache=Object.create(null)));var b=u[a];if(b)a=b;else{t.href=a;t.protocol||(t.href=t.href);b={href:t.href,protocol:t.protocol,host:t.host,hostname:t.hostname,port:"0"==t.port?"":t.port,pathname:t.pathname,search:t.search,hash:t.hash,origin:null};"/"!==b.pathname[0]&&(b.pathname="/"+b.pathname);if("http:"==b.protocol&&80==b.port||"https:"==b.protocol&&443==b.port)b.port="",b.host=b.hostname;b.origin=
t.origin&&"null"!=t.origin?t.origin:"data:"!=b.protocol&&b.host?b.protocol+"//"+b.host:b.href;a=u[a]=b}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function w(a,b){var c;c=void 0===c?"source":c;m().assert(null!=a,"%s %s must be available",b,c);var d=a;m().assert(v(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d};function x(a){AMP.BaseElement.apply(this,arguments)}e(x,AMP.BaseElement);x.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
x.prototype.buildCallback=function(){this.a=this.win.document.createElement("div");this.applyFillContent(this.a,!0);this.element.appendChild(this.a);this.a.hasAttribute("role")||this.a.setAttribute("role","list");var a;a:{var b=this.getAmpDoc();if(b.nodeType){var c=(b.ownerDocument||b).defaultView;if(c=c!=(c.__AMP_TOP||c)&&c.services&&c.services["url-replace"]?p(c,c,"url-replace"):null){a=c;break a}}c=r(b);b=r(b);(b=b.isSingleDoc()?b.win:b)&&b.services&&b.services["url-replace"]&&(a=p(b,c,"url-replace"))}this.c=
a};x.prototype.reconstructWhenReparented=function(){return!1};
x.prototype.layoutCallback=function(){var a=this;return this.c.expandAsync(w(this.element.getAttribute("src"),this.element)).then(function(b){var c={};a.element.hasAttribute("credentials")&&(c.credentials=a.element.getAttribute("credentials"));c.credentials||(c.requireAmpResponseSourceOrigin=!1);return n(a.win,"batched-xhr").fetchJson(b,c)}).then(function(b){m().assert(null!=b,"Response is undefined %s",a.element);var c=a.element.getAttribute("items")||"items",d;d=c;if("."==d)d=b;else{d=d.split(".");
for(var f=b,g=0;g<d.length;g++){var h=d[g];if(!h){f=void 0;break}if("[object Object]"!==k.call(f)||void 0===f[h]||null==f||"object"!=typeof f||!Object.prototype.hasOwnProperty.call(f,h)){f=void 0;break}f=f[h]}d=f}var q=d;m().assert(q&&Array.isArray(q),'Response must contain an array at "%s". %s %s',c,a.element,b);return n(a.win,"templates").findAndRenderTemplateArray(a.element,q).then(a.b.bind(a))})};
x.prototype.b=function(a){var b=this;a.forEach(function(a){a.hasAttribute("role")||a.setAttribute("role","listitem");b.a.appendChild(a)});this.getVsync().measure(function(){var a=b.a.scrollHeight;a>b.element.offsetHeight&&b.attemptChangeHeight(a).catch(function(){})})};AMP.registerElement("amp-list",x);
})});
//# sourceMappingURL=amp-list-0.1.js.map
