(self.AMP=self.AMP||[]).push({n:"amp-iframe",v:"1492569253368",f:(function(AMP){var k;function l(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]};Date.now();self.log=self.log||{user:null,dev:null};var p=self.log;function u(){if(p.user)return p.user;throw Error("failed to call initLogConstructor");}function v(){if(p.dev)return p.dev;throw Error("failed to call initLogConstructor");};function x(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};function y(a){var b,d=a=a.__AMP_TOP||a,c=b?b:void 0,e=a.services;e||(e=a.services={});a=e;(e=a.timer)||(e=a.timer={obj:null,promise:null,resolve:null,build:null});e.obj||(e.obj=e.build?e.build():c(d),e.resolve&&e.resolve(e.obj));return e.obj};function z(a,b){var d=a.length-b.length;return 0<=d&&a.indexOf(b,d)==d};var A=(self.AMP_CONFIG||{}).thirdPartyFrameHost||"ampproject.net";var C,D;
function E(a){var b;C||(C=self.document.createElement("a"),D=self.UrlCache||(self.UrlCache=Object.create(null)));var d=D[a];if(d)return d;C.href=a;C.protocol||(C.href=C.href);var c={href:C.href,protocol:C.protocol,host:C.host,hostname:C.hostname,port:"0"==C.port?"":C.port,pathname:C.pathname,search:C.search,hash:C.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=C.origin&&"null"!=
C.origin?C.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;var e=c;return b?e:D[a]=e}function F(a){"string"==typeof a&&(a=E(a));return"https:"==a.protocol||"localhost"==a.hostname||z(a.hostname,".localhost")};var G,H="Webkit webkit Moz moz ms O o".split(" ");function I(a,b){var d,c=a.style;G||(G=x());var e=G.zIndex;if(!e){e="zIndex";if(void 0===c.zIndex){var f="Z"+"zIndex".slice(1);a:{for(var g=0;g<H.length;g++){var h=H[g]+f;if(void 0!==c[h]){f=h;break a}}f=""}void 0!==c[f]&&(e=f)}G.zIndex=e}(c=e)&&(a.style[c]=d?b+d:b)};var J={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0};function K(a,b,d,c){return{left:a,top:b,width:d,height:c,bottom:b+c,right:a+d}}function L(a){for(var b=-Infinity,d=Infinity,c=-Infinity,e=Infinity,f=0;f<arguments.length;f++){var g=arguments[f];if(g&&(b=Math.max(b,g.left),d=Math.min(d,g.left+g.width),c=Math.max(c,g.top),e=Math.min(e,g.top+g.height),d<b||e<c))return null}return Infinity==d?null:K(b,c,d-b,e-c)}function M(a,b,d){return 0==b&&0==d||0==a.width&&0==a.height?a:K(a.left+b,a.top+d,a.width,a.height)};function aa(a,b){try{return JSON.parse(a)}catch(d){b&&b(d)}};function ba(a){if(!N(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(d){return v().error("MESSAGING","Failed to parse message: "+a,d),null}}function N(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function ca(a,b){for(var d=[],c=0;c<a.length;c++){var e=a[c];b(e,c,a)||(d.push(e),a.splice(c,1),c--)}};function O(a,b,d){var c=a.listeningFors;!c&&d&&(c=a.listeningFors=Object.create(null));a=c||null;if(!a)return a;var e=a[b];!e&&d&&(e=a[b]=[]);return e||null}function da(a,b,d){var c=E(b.src).origin,e=d?b.getAttribute("data-amp-3p-sentinel"):"amp";a=O(a,e,!0);for(var f,e=0;e<a.length;e++){var g=a[e];if(g.frame===b){f=g;break}}f||(f={frame:b,origin:c,events:Object.create(null)},a.push(f));return f.events}
function ea(a){for(var b={sentinel:"unlisten"},d=a.length-1;0<=d;d--){var c=a[d];if(!c.frame.contentWindow){a.splice(d,1);var e=c.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function fa(a){if(!a.listeningFors){var b=function(b){if(b.data){var c=ga(b.data);if(c&&c.sentinel){var d;d=c.sentinel;var f=b.origin,g=b.source,h=O(a,d);if(h){for(var q,m=0;m<h.length;m++){var t=h[m],r=t.frame.contentWindow;if(r)if("amp"===d){if(t.origin===f&&r==g){q=t;break}}else{var n;if(!(n=g==r))b:{for(n=g;n&&n!=n.parent;n=n.parent)if(n==r){n=!0;break b}n=!1}if(n){q=t;break}}else setTimeout(ea,0,h)}d=q?q.events:null}else d=h;var B=d;if(B){var w=B[c.type];if(w)for(w=w.slice(),d=0;d<w.length;d++)(0,w[d])(c,
b.source,b.origin)}}}};a.addEventListener("message",b)}}function P(a,b,d,c,e){function f(b,c,f){if(e||c==a.contentWindow)"unlisten"==b.sentinel?q():d(b,c,f)}var g=a.ownerDocument.defaultView;fa(g);c=da(g,a,c);var h=c[b]||(c[b]=[]),q;h.push(f);return q=function(){if(f){var a=h.indexOf(f);-1<a&&h.splice(a,1);d=h=f=null}}}
function ha(a,b,d,c,e){if(a.contentWindow){c.type=d;c.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp";var f=c;e&&(f="amp-"+JSON.stringify(c));for(a=0;a<b.length;a++)d=b[a],d.win.postMessage(f,d.origin)}}function ga(a){"string"==typeof a&&(a="{"==a.charAt(0)?aa(a,function(a){v().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:N(a)?ba(a):null);return a}
function Q(a,b,d,c){var e=this;this.a=a;this.u=d;this.f=[];this.M=P(this.a,b,function(a,b,d){e.f.some(function(a){return a.win==b})||e.f.push({win:b,origin:d});c(a,b,d)},this.u,this.u)}Q.prototype.send=function(a,b){ca(this.f,function(a){return!!a.win.parent});ha(this.a,this.f,a,b,this.u)};Q.prototype.destroy=function(){this.M();this.f.length=0};var ia=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1],ja=Date.now();function R(a,b,d){var c=this;this.m=a;this.g=null;this.A=this.F=!1;this.j=null;this.l=a.getViewport();this.G=new Q(b,"send-intersections",d||!1,function(){ka(c)});this.g=new S(function(a){for(var b=0;b<a.length;b++)delete a[b].target;c.G.send("intersection",{changes:a})},{threshold:ia});this.g.tick(this.l.getRect());this.fire=function(){c.F&&c.A&&c.g.tick(c.l.getRect())}}
function ka(a){a.F=!0;a.g.observe(a.m.element);a.m.getVsync().measure(function(){a.A=a.m.isInViewport();a.fire()});var b=a.l.onScroll(a.fire),d=a.l.onChanged(a.fire);a.j=function(){b();d()}}R.prototype.onViewportCallback=function(a){this.A=a};R.prototype.destroy=function(){this.F=!1;this.g=null;this.j&&(this.j(),this.j=null);this.G.destroy();this.G=null};function S(a,b){this.I=a;var d=b&&b.threshold||[0];this.L=d.sort();this.C=null;this.K=void 0;this.b=[]}
S.prototype.disconnect=function(){this.b.length=0};S.prototype.observe=function(a){for(var b=0;b<this.b.length;b++)if(this.b[b].element===a){v().warn("INTERSECTION-OBSERVER","should observe same element once");return}var d={element:a,currentThresholdSlot:0};this.C&&(a=T(this,d,this.C,this.K))&&this.I([a]);this.b.push(d)};S.prototype.unobserve=function(a){for(var b=0;b<this.b.length;b++)if(this.b[b].element===a){this.b.splice(b,1);return}v().warn("INTERSECTION-OBSERVER","unobserve non-observed element")};
S.prototype.tick=function(a,b){b&&(a=M(a,-b.left,-b.top),b=M(b,-b.left,-b.top));this.C=a;this.K=b;for(var d=[],c=0;c<this.b.length;c++){var e=T(this,this.b[c],a,b);e&&d.push(e)}d.length&&this.I(d)};
function T(a,b,d,c){var e=b.element,f,g=null;f=e.getLayoutBox();var h=e.getOwner(),g=h&&h.getLayoutBox(),q=L(f,g,d,c)||K(0,0,0,0),h=q,m=f,h=h.width*h.height/(m.width*m.height);a=a.L;var m=0,t=a.length;if(0==h)a=0;else{for(var r=(m+t)/2|0;m<r;)h<a[r]?t=r:m=r,r=(m+t)/2|0;a=t}var n=a;if(n==b.currentThresholdSlot)return null;b.currentThresholdSlot=n;d=c?null:d;c=q;a=f;if(m=d)c=M(c,-d.left,-d.top),a=M(a,-d.left,-d.top),m=M(m,-d.left,-d.top);var B={time:"undefined"!==typeof performance&&performance.now?
performance.now():Date.now()-ja,rootBounds:m&&U(m),boundingClientRect:U(a),intersectionRect:U(c),intersectionRatio:h,target:e};return B}function U(a){return{left:a.left,top:a.top,width:a.width,height:a.height,bottom:a.bottom,right:a.right,x:a.left,y:a.top}};var la="allowfullscreen allowpaymentrequest allowtransparency frameborder referrerpolicy scrolling".split(" "),ma=0,V=0;function W(a){AMP.BaseElement.apply(this,arguments)}l(W,AMP.BaseElement);k=W.prototype;k.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
k.assertSource=function(a,b,d){var c=E(a);u().assert(F(c)||"data:"==c.protocol,"Invalid <amp-iframe> src. Must start with https://. Found %s",this.element);var e=E(b);u().assert(!(" "+d+" ").match(/\s+allow-same-origin\s+/i)||c.origin!=e.origin&&"data:"!=c.protocol,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",this.element);u().assert(!(z(c.hostname,"."+A)||
z(c.hostname,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",a);return a};
k.assertPosition=function(){var a=this.element.getLayoutBox(),b=Math.min(600,.75*this.getViewport().getSize().height);u().assert(a.top>=b,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",this.element,
a.top,b)};function X(a){if(a){var b=E(a);"data:"==b.protocol||b.hash&&"#"!=b.hash||(b=a.indexOf("#"),a=(-1==b?a:a.substring(0,b))+"#amp=1");return a}}
k.firstAttachedCallback=function(){this.i=this.element.getAttribute("sandbox");var a;if(!(a=X(this.element.getAttribute("src")))){a=this.element.getAttribute("srcdoc");var b=this.i;if(a){u().assert(!(" "+b+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)a=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));for(var b=new Uint8Array(a.length),d=0;d<a.length;d++){var c=a.charCodeAt(d);
b[d]=c}a=b}a="data:text/html;charset=utf-8;base64,"+btoa(String.fromCharCode.apply(String,a))}else a=void 0}var e=a;this.iframeSrc=this.assertSource(e,window.location.href,this.i);a=this.element;"no"!=a.getAttribute("scrolling")&&(b=a.ownerDocument.createElement("i-amphtml-scroll-container"),a.appendChild(b),a=b);this.o=a};k.preconnectCallback=function(a){this.iframeSrc&&this.preconnect.url(this.iframeSrc,a)};
k.buildCallback=function(){this.D=this.getPlaceholder();this.w=!!this.D;this.J=this.h=this.v=!1;this.a=this.s=this.N=null;(this.B=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.c=null;this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0")};
k.onLayoutMeasure=function(){Y(this);var a;a:{var b=this.element.getLayoutBox();a=b.height;for(var b=b.width,d=0;d<Z.length;d++){var c=Z[d][0],e=Z[d][1];if(!(e>a||c>b)&&20>=a-e&&20>=b-c){a=!0;break a}}a=!1}this.v=a;a=this.element.getLayoutBox();this.h=10<a.width&&10<a.height?!1:!0;if(a=this.v){a=this.win;b=!1;d=0;c=this.element;do J[c.tagName]?(d++,b=!1):(e=(a.getComputedStyle(c)||x()).position,"fixed"!=e&&"sticky"!=e||(b=!0)),c=c.parentElement;while(c&&"BODY"!=c.tagName);a=!(!b&&1>=d)}this.J=a;this.c&&
this.c.fire()};function Y(a){if(a.a){var b=a.getViewport().getLayoutRect(a.a),d=a.getLayoutBox();a.s=M(b,-d.left,-d.top)}}k.getIntersectionElementLayoutBox=function(){if(!this.a)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.s||Y(this);return M(this.s,a.left,a.top)};
k.layoutCallback=function(){var a=this;u().assert(!this.J,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.w||this.assertPosition();this.B&&u().assert(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return Promise.resolve();if(this.h&&(V++,1<V))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
Promise.resolve();var b=this.element.ownerDocument.createElement("iframe");this.a=b;this.applyFillContent(b);b.name="amp_iframe"+ma++;this.w&&I(b,-1);this.propagateAttributes(la,b);na(b,this.i);b.src=this.iframeSrc;this.h||(this.c=new R(this,b));b.onload=function(){b.readyState="complete";a.H();a.h&&(a.iframeSrc=null,y(a.win).promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);a.element.setAttribute("amp-removed","");a.a=null}))};P(b,"embed-size",function(b){oa(a,b.height,
b.width)});this.w&&P(b,"embed-ready",this.H.bind(this));this.o.appendChild(b);return this.loadPromise(b).then(function(){a.o!=a.element&&y(a.win).delay(function(){a.deferMutate(function(){a.o.classList.add("amp-active")})},1E3)})};k.unlayoutOnPause=function(){return!0};k.unlayoutCallback=function(){if(this.a){var a=this.a;a.parentElement&&a.parentElement.removeChild(a);this.D&&this.togglePlaceholder(!0);this.a=null;this.c&&(this.c.destroy(),this.c=null)}return!0};k.viewportCallback=function(a){if(this.c)this.c.onViewportCallback(a)};
k.getPriority=function(){return this.v?2:this.h?1:AMP.BaseElement.prototype.getPriority.call(this)};k.mutatedAttributesCallback=function(a){var b=a.src;void 0!==b&&(this.iframeSrc=X(b),this.a&&(this.a.src=this.assertSource(this.iframeSrc,window.location.href,this.i)))};k.H=function(){var a=this;this.D&&this.getVsync().mutate(function(){a.a&&(I(a.a,0),a.togglePlaceholder(!1))})};k.firstLayoutCompleted=function(){};
function oa(a,b,d){if(a.B)if(100>b)u().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var c,e;b=parseInt(b,10);isNaN(b)||(c=Math.max(b+(a.element.offsetHeight-a.a.offsetHeight),b));d=parseInt(d,10);isNaN(d)||(e=Math.max(d+(a.element.offsetWidth-a.a.offsetWidth),d));void 0!==c||void 0!==e?a.attemptChangeSize(c,e).then(function(){void 0!==c&&a.element.setAttribute("height",
c);void 0!==e&&a.element.setAttribute("width",e)},function(){}):u().error("amp-iframe","Ignoring embed-size request becauseno width or height value is provided",a.element)}else u().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element)}function na(a,b){var d=b||"";a.setAttribute("sandbox",d)}var Z=[[300,250],[320,50],[300,50],[320,100]];AMP.registerElement("amp-iframe",W);
})});
//# sourceMappingURL=amp-iframe-0.1.js.map
